### ISSUE TITLE
Probeer je CSS herbruikbaar te maken

### ISSUE THREAD

**Issue by krijnhoetmer** [RenzoWille/i-love-web#9]
Je hebt in `about.css`, `learningjournal.css` en `styles.css` veel dubbele code staan: dit kan waarschijnlijk handiger.

**Comment by krijnhoetmer** [comment]
Zelfde geldt voor JS :)

**Comment by RenzoWille** [comment]
https://github.com/RenzoWille/i-love-web/commit/a7f26901158b7f73b54efd0cad374ff8c0e91fbd

**Comment by krijnhoetmer** [comment]
Kleine pro-tip nog: partial commits; https://github.blog/news-insights/product-news/partial-commits-in-github-for-windows/ en https://docs.github.com/en/desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop#creating-a-partial-commit
